### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by RichardsonWTR** [crisdanna/goldenhour#4]
- [x] Fix the application by adding or removing the missing component
- [ ] Get the questionnaire result and show the different pages
- [x] Change the app name
- [x] Change the app icon
- [x]  Fix the broken tests
- [x] Reduce the duplicated code by creating new components
